### ISSUE TITLE
Duplicate screen output from various steps to files...

### ISSUE THREAD

**Issue by fruviad** [StateLibraryofOhio/slo_dpla_postprocessing#3]
Currently, the scripts dump to screen the commands needed to run the next script in the series.  Running one of the commands can cause the 2nd command to scroll beyond the end of the screen buffer.

Re-running the commands can be extremely time-consuming for larger data-sets.  The screen output from the scripts should be dumped to files, also.

**Comment by slodplaadmin** [comment]
replaced   

```cat <<EOF```

with

```tee filename.txt <<EOF```
